# config/collect_data.yaml に追加
defaults:
  - vehicle: default
  - envs: default 
  - planner: pure_pursuit


output_dir: ./datasets/
num_episodes: 100
num_steps: 15000
render: false
render_mode: human_fast

data:
  num_waypoints: 10

hydra:
  run:
    dir: ./outputs/collect_data/${now:%Y-%m-%d}/${now:%H-%M-%S}