num_epochs: 100

dataset:
  path: ./datasets
  batch_size: 32
  num_workers: 0

  target_points: 1080
  max_steer: 0.4
  min_speed: 0.0
  max_speed: 10.0

model:
  name: N4LidarGCN
  input_dim: 2
  hidden_dim: 128
  output_dim: 2
  pool_method: mean ## mean or max

training:
  lr: 1e-3
  log_interval: 10
  checkpoint_dir: ./ckpts
  checkpoint_filename: best_model.pth
  early_stop_patience: 5   # 改善がなければ何エポックで打ち切るか

hydra:
  run:
    dir: ./outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}